version: '2'
services:
  stns:
    image: stns/stns:latest
    container_name: stns
    volumes:
      - ./stns.conf:/etc/stns/server/stns.conf
      - ./stns/conf.d:/etc/stns/conf.d
    ports:
      - 1104:1104
