version: '2'
services:
  stns:
    image: stns/stns:latest
    container_name: stns
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./stns.conf:/etc/stns/server/stns.conf
      - ./conf.d:/etc/stns/conf.d
    ports:
      - 1104:1104
