version: '2'
services:
  stns-vmlmachines:
    image: stns/stns:latest
    container_name: stns-vmlmachines
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./stns.conf:/etc/stns/server/stns.conf
      - ./vmlmachines-conf.d:/etc/stns/conf.d
    ports:
      - 1104:1104

  stns-vmlbastion:
    image: stns/stns:latest
    container_name: stns-vmlbastion
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - ./stns.conf:/etc/stns/server/stns.conf
      - ./vmlbastion-conf.d:/etc/stns/conf.d
    ports:
      - 1105:1104
